# Generated by Django 3.1.4 on 2020-12-28 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 28, 13, 22, 10, 853249)),
        ),
        migrations.AlterField(
            model_name='ebay',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 28, 13, 22, 10, 853249)),
        ),
        migrations.AlterField(
            model_name='flipkart',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 28, 13, 22, 10, 852229)),
        ),
    ]
