# Generated by Django 3.1.4 on 2021-01-21 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceTracker', '0002_auto_20201228_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 0, 9, 5, 744198)),
        ),
        migrations.AlterField(
            model_name='ebay',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 0, 9, 5, 744198)),
        ),
        migrations.AlterField(
            model_name='flipkart',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 0, 9, 5, 743196)),
        ),
    ]
